import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Nextjs from "../public/nextjs-icon.png";
import Pocketbase from "../public/pocketbase-icon.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />

      <main className={styles.main}>
          <h1 className={styles.title}>
              Fully Responsive CRUD App built with <br/>
              <a className={styles.logo} href="https://nextjs.org"><Image src={Nextjs} alt={Nextjs} /></a> and
              <a className={styles.logo} href="https://pocketbase.io"><Image src={Pocketbase} alt={"Pocketbase"} /></a>
          </h1>
          <h6 className={styles.description}>You can register new users, login, add profile image 2x2, and change other user settings</h6>
          <p className={styles.description}>Work in progress</p>
      </main>

        <Footer />
    </div>
  )
}
