import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react";
import pb from "../lib/pocketbase";
import {AuthContext} from "../context/authContext";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function Home() {

    const { currentUser, logout } = React.useContext(AuthContext);

    console.log(currentUser);

  return (
    <div className={styles.container}>
      <Head>
        <title>CRUD Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />

      <main className={styles.main}>
      </main>

        <Footer />
    </div>
  )
}
